DELETE http://localhost:3001/api/blogs/64b13ffd88aeb46facbb0cc4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZvaHkiLCJpZCI6IjY0YjEyNTYzMTI1NmM5NjM4MzdiYTYwMSIsImlhdCI6MTY4OTM0MjMwOCwiZXhwIjoxNjg5MzQ1OTA4fQ.BJBCz2WQRaY-s3azTRMSh0VAQPpRV7CAe-lR96QrKTw